apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ledger.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ledger.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ledger.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ledger.name" . }}
    spec:
      containers:
        - name: ledger-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: "{{ $v }}"
            {{- end }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
