apiVersion: v1
kind: Service
metadata:
  name: {{ include "ledger.fullname" . }}-api
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "ledger.name" . }}
    app.kubernetes.io/component: api
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
